### PR TITLE
Added chrome extension & mariokart music

### PR DESCRIPTION
**Pull request by benf2004**
Hi! I added a Chrome extension version of your script to make it more accessible (I have paid for a Chrome web store developer account so I can submit it and credit you if you'd like). 

The script will also now play [the winner Mariokart Wii music](https://downloads.khinsider.com/game-soundtracks/album/mario-kart-wii/3-37%2520Trophy%2520Presentations%2520%2528Shorter%2529.mp3) if you get a 3, 4, or 5 and will play [No Trophy for You](https://downloads.khinsider.com/game-soundtracks/album/mario-kart-wii/2-18%2520No%2520Trophy%2520for%2520You%2521.mp3) if you get a 1 or a 2.

### CODE REVIEW

**Comment by benf2004** [comment]
(I didn't touch the tampermonkey script, only the chrome extension plays mariokart music)

**Comment by benf2004** [comment]
View new demo: https://www.youtube.com/watch?v=u_V7EO44Qxs

**Comment by Samathingamajig** [comment]
I'm not completely sure what to do about the sound effects, many people have requested different things. I want there to be customization for it, but I wonder if users want that kind of customization for a script used for 2 minutes a year

**Comment by Samathingamajig** [comment]
What's the source of the icon? It needs to be credited, and if it's you then that will still need to be mentioned somewhere (doesn't need to be in this PR). If it's not by you, then we need to make sure it's ok to use.

The icon looks good, but it's not centered. The bottom is clipped off and the other edges don't have the same amount of pixels away from the edge.

**Comment by Samathingamajig** [comment]
Last time I checked (several years ago), the fee for a developer account was $25 I think, now that it's $5 I'm fine with paying that for myself for when I make more extensions

**Comment by benf2004** [comment]
The icon was made with DALLE, no credit is needed.

Up to you for the music! You could also add a license so there could be different versions of it.

**Comment by Samathingamajig** [comment]
Here's the logo centered w/ a perfect circle, and transparent background (i added a white outline)




For this PR, if you can update the image(s) and remove the sound effects (for now) I'll merge it

**Comment by benf2004** [comment]
Done!

**Comment by Samathingamajig** [comment]
Thanks for your contribution!

**Pull request merged**
