### PR TITLE
feat: Adds custom sound effects in Chrome extension (closes #2)

### LINKED ISSUE #2: RFC: Sound effects ideas
WIP

Some thoughts I've had on adding sound effects.

## Positive
- Charlie "WOOO YEAH BABY!! THAT'S WHAT I'VE BEEN WAITING FOR, THAT'S WHAT IT'S ALL ABOUT" https://youtu.be/sAXZbfLzJUg
- Noice https://youtu.be/a8c5wmeOL9o
- Super Mario Bros flag pole https://youtu.be/3BsBXp6VkvU
- Mario Kart Wii trophy https://youtu.be/u_V7EO44Qxs?t=18
- 

## Negative
- Charlie "It was a misinput" https://youtu.be/tjOAqCIIaAw
- Sad trombone
-

Should it be a random sound or customizable? Should specific sounds be for each possible score (5 different total sounds)?

Also, would a delay be good, such as with the Jaws sound effect and reveal the score afterwards (this sound wouldn't be dependent on scores)

### PR DESCRIPTION
**Pull request by benf2004**
I added an options page to select your sound effect choices for each score (including a "None" option). It should open automatically upon installation or upon clicking the extension icon.

screely-1688082484448

Feel free to adjust the CSS. I was going for a "Peaches & Cream" vibe. 

In order to play the audio within the content script of the AP score page, you have to inject an iframe to get around collegeboard.com's content security policy. It's a bit of a jerry rig but it works like a charm. 

PS sorry that the commit history got a bit wacky... not sure what happened.

### CODE REVIEW

**Comment by benf2004** [comment]
Closes #2

**Comment by Samathingamajig** [comment]
Looks good for the most part. If you're available to make a few changes
- Create all the Audio objects at the beginning (either just the ones needed for the scores, or all of the selected audio even if there's not a particular score, say no 2 or 3, to make it easier to test by changing HTML, and also easier to make) and just send the score through the function to the iframe, that way the sound effect plays immediately and not with delay
- Add a blank line at the end of files that don't have it, see https://stackoverflow.com/a/5813359/12101554 for more info, and also it messes with Git if you add something at the end without having the blank line since it thinks you've modified the last line
- Add a "Thanks you for installing" on the first launch, probably with a simple query parameter `?justInstalled=true`
- Add the all rights reserved symbol ® and change Reveal -> Hider to make it "AP® Score Hider Settings" and add the disclaimer at the bottom "AP® is a trademark registered by the College Board, which is not affiliated with, and does not endorse, this product."
- (optional) Directly "upload" mp3 files on disk, might need file reading permissions or something, not sure exactly how MV3 handles reading files, especially when selected by a user

If you're not, let me know and I can get those tonight. If you have Discord, you can contact me faster and less formally at @samathingamajig (same as github)

**Comment by benf2004** [comment]
Yeah, I can make those changes really quick.

**Comment by benf2004** [comment]
I don't think storing files locally in the Chrome extension itself is going to be feasible. At least I can't figure out how to do it.

**Comment by Samathingamajig** [comment]
You can store data URLs it in `chrome.storage.local` https://developer.chrome.com/docs/extensions/reference/storage/#:~:text=buckets%20(%22storage%20areas%22)%3A-,storage.local,-Data%20is%20stored, which will allow for more data (described below) but doesn't synchronize against all browsers (then again, don't really need that). `chrome.storage.sync` has a hard limit of 100kb, "approx 8kb per entry", which wont fit mp3s, which take 24KB/s at medium quality, according to one source, but usually higher.

With the `"unlimitedStorage"` permission, we can store as many mp3s as they want. With this, it needs a way to delete individual audio files and all of them at once.

Here's example code from ChatGPT 4
```javascript
document.getElementById('audioFile').addEventListener('change', function(event) {
    var file = event.target.files[0];
    if (file) {
        var reader = new FileReader();
        reader.onload = function(e) {
            var audio = new Audio(e.target.result);
            audio.play();

            // Save the audio file to chrome.storage.sync
            chrome.storage.sync.set({savedAudio: e.target.result}, function() {
                console.log("Audio saved to chrome.storage.sync");
            });
        };
        reader.readAsDataURL(file);
    }
});

// Load the saved audio file when the browser restarts
window.addEventListener('DOMContentLoaded', function() {
    chrome.storage.sync.get('savedAudio', function(data) {
        if (data.savedAudio) {
            var audio = new Audio(data.savedAudio);
            audio.play();
        }
    });
});
```

Once again, thanks for this. If you're able to get this done tonight, I'll submit it for approval, hopefully it gets approved before score day (upcoming Wednesday).

**Comment by benf2004** [comment]
Working on it right now...

**Comment by benf2004** [comment]
@Samathingamajig I finished! Package it up and ship it ASAP! 

(also it's kind of a mess but I did what I could with time)

**Comment by Samathingamajig** [comment]
Thanks, once again. I've noticed a few bugs that are easy to fix that I will handle myself
- Clicking another result that has the same score seems to have no effect on the audio, but that's because it's pausing the audio but never restarting it. Adding a simple `sounds[score].audio.currentTime = 0;` is good enough
- It's possible to submit a sound without typing in a title. if uploading a file, it's easy to just take that filename, for the audio link probably will just show an error "enter a title" (how are duplicate names handled, if at all?)

Please Chrome Web Store team, don't have a four-day holiday

**Comment by Samathingamajig** [comment]
I've submitted it for review

**Comment by Samathingamajig** [comment]
Posted on reddit: https://www.reddit.com/r/APStudents/comments/14oaxya/ap_score_hider_has_sound_effects_now/?utm_source=share&utm_medium=web2x&context=3

**Comment by benf2004** [comment]
@Samathingamajig FYI I am u/OA2Gsheets on Reddit. Glad the Chrome Webstore worked fast on this one 🥳

**Comment by benf2004** [comment]
https://chrome.google.com/webstore/detail/ap%C2%AE-score-hider/jfeofgolbklfnkjdogghbmbgnonkgace/

**Pull request merged**
